[program:propfincrm-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/propfincrm/artisan queue:work database --queue=integrations,default --sleep=3 --tries=3 --timeout=90 --max-time=3600
directory=/var/www/propfincrm
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/propfincrm-worker.log
stopwaitsecs=120
