export const Endpoints = {
  LOGIN: 'API/login.php',
  LEADS_COUNT: 'API/LeadsCount.php',
  CHECK_CHECKIN: 'API/check_checkin.php',
  EMPLOYEE_CHECKIN_CHECKOUT: 'API/employee_checkin_checkout.php',
  LEADS_FILTER: 'API/Leads_Filter.php',
  LEADS_LIST: 'API/Leads_list.php',
  LEADS_DETAIL: 'API/Leads_Detail.php',
  PREVIOUS_FOLLOWUP: 'API/previous_followup.php',
  ADD_NEW_FOLLOWUP: 'API/addnewfollowup.php',
  MASTER: 'API/master.php',
  NEW_LEAD: 'API/newlead.php',
  USER_FOLLOWUPS: 'API/userfollowups.php',
  ADD_CALL_LOGS: 'API/addcalllogs.php',
  CALL_LOGS: 'API/calllogs.php',
  USER_NOTIFICATIONS: 'API/usernotifications.php',
  NOTIFICATION_READ: 'API/notification_read.php',
  SENIOR: 'API/Senior.php',
  LEAD_STATUS: 'API/Lead_status.php',
  MEETING_TYPE: 'API/Meeting_Type.php',
  ADD_FOLLOWUP_MEETING: 'API/addfollowupmeeting.php',
  LEAD_UPDATE: 'API/leadupdate.php',
};
